package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"

	"coordinator/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Spot)
// DB Table: Plural (spots)
// Resource: Plural (Spots)
// Path: Plural (/spots)
// View Template Folder: Plural (/templates/spots/)

// SpotsResource is the resource for the Spot model
type SpotsResource struct {
	buffalo.Resource
}

// List gets all Spots. This function is mapped to the path
// GET /spots
func (v SpotsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	spots := &models.Spots{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Spots from the DB
	if err := q.All(spots); err != nil {
		return err
	}

	return c.Render(200, r.JSON(spots))
}

// Show gets the data for one Spot. This function is mapped to
// the path GET /spots/{spot_id}
func (v SpotsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Spot
	spot := &models.Spot{}

	// To find the Spot the parameter spot_id is used.
	if err := tx.EagerPreload().Find(spot, c.Param("spot_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return c.Render(200, r.JSON(spot))
}

// Create adds a Spot to the DB. This function is mapped to the
// path POST /spots
func (v SpotsResource) Create(c buffalo.Context) error {
	// Allocate an empty Spot
	spot := &models.Spot{}

	// Bind spot to the html form elements
	if err := c.Bind(spot); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(spot)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
	}

	return c.Render(http.StatusCreated, r.JSON(spot))
}

// Update changes a Spot in the DB. This function is mapped to
// the path PUT /spots/{spot_id}
func (v SpotsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Spot
	spot := &models.Spot{}

	if err := tx.Find(spot, c.Param("spot_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Spot to the html form elements
	if err := c.Bind(spot); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(spot)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
	}

	return c.Render(http.StatusOK, r.JSON(spot))
}

// Destroy deletes a Spot from the DB. This function is mapped
// to the path DELETE /spots/{spot_id}
func (v SpotsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Spot
	spot := &models.Spot{}

	// To find the Spot the parameter spot_id is used.
	if err := tx.Find(spot, c.Param("spot_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(spot); err != nil {
		return err
	}

	return c.Render(http.StatusOK, r.JSON(spot))
}
