# Generated by Django 4.0.2 on 2022-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_rename__id_area_id_rename__id_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='banned_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
