# Generated by Django 4.0.2 on 2022-02-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_alter_member_banned_until_alter_ticket_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
