# Generated by Django 4.0.2 on 2022-02-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0004_alter_member_banned_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to='coordinator.ticket'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='spots', to='coordinator.area'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='coordinator.member'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='coordinator.spot'),
        ),
    ]
