# Generated by Django 4.0.2 on 2022-03-04 05:09

from django.db import migrations, models
import django.utils.timezone
import storage_management.coordinator.utils


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0005_alter_notification_ticket_alter_spot_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expires_at',
            field=models.DateTimeField(default=storage_management.coordinator.utils.seven_days),
        ),
        migrations.AddConstraint(
            model_name='spot',
            constraint=models.UniqueConstraint(fields=('area', 'name'), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at', None)), fields=('member',), name='unique_member'),
        ),
    ]
